### PR TITLE
adding a few more symbols

### PR DESCRIPTION
**Pull request by taurean**
adding a few more fractions, multiplication symbol, and the apple logo

### CODE REVIEW

**Review by samwho — APPROVED** [review]
🫡🙏

**Comment by samwho** [comment]
Ah, sorry, I made a merge conflict merging another PR before this one. Request another review when it's fixed and I'll get this in ❤️

**Comment by samwho** [comment]
I added times and the Apple symbol in https://github.com/samwho/symbol.wtf/commit/3f430b7e7207339628b511364aba58ae3b3542ee and added you as a co-author so you are appropriately credited.

Going to hold off on the extra fractions for the time being, want to be careful not to accept too many symbols too fast.

Thanks for your contribution! 🙏

**Comment by taurean** [comment]
makes sense! thanks for getting to this before I could.

**Pull request closed without merging**
