### PR TITLE
Make the symbols keyboard accessible

### PR DESCRIPTION
**Pull request by bbeaudry**
Many people prefer to use a keyboard or cannot use a pointer device, like a mouse or trackpad. This PR makes the symbols keyboard focusable, and invokable via the "Enter" or "Space" key.

### CODE REVIEW

**Comment by samwho** [comment]
Hey @bbeaudry, sorry about the merge conflicts here. I'm keen to see how this would look with the latest changes, are you able to update this PR? 🙏

**Comment by qwell** [comment]
I got it -- one sec!  Will have to do a new PR though.

**Comment by samwho** [comment]
@qwell let's give @bbeaudry a shot at this. There's no rush 🙂

**Comment by bbeaudry** [comment]
Updated the PR. Ready for review!

**Review by qwell — APPROVED** [review]
I tested this and it works quite nicely.

**Comment by samwho** [comment]
Just gave it a whirl myself, works great! Thank you @bbeaudry.

**Pull request merged**
