### PR TITLE
add home directory of the user

### PR DESCRIPTION
**Pull request by Carfox**
cd ~

### CODE REVIEW

**Comment by qwell** [comment]
Are there any keyboards (mobile or otherwise) where tilde isn't available?

**Comment by Carfox** [comment]
> Are there any keyboards (mobile or otherwise) where tilde isn't available?

On a spanish keyboard.

**Comment by autinerd** [comment]
Spanish has ~ on AltGr+4 🤔

**Comment by samwho** [comment]
Added this in https://github.com/samwho/symbol.wtf/commit/1d02ce72fedde696a0fa209210eac2136e8c4049 and made sure to add you as a co-author so you get credit. Thank you for you contribution! 🙏

**Pull request closed without merging**
