### PR TITLE
Adding US dollar symbol

### PR DESCRIPTION
**Pull request by otobrglez**
Adding the [US dollar symbol](https://en.wikipedia.org/wiki/United_States_dollar).

### CODE REVIEW

**Review by bee-san — APPROVED** [review]
This does not appear to be a US dollar symbol but instead the Tongan paʻanga Symbol. However, since the US uses the same symbol as Tonga this should be merged.

**Comment by qwell** [comment]
That could get incredibly confusing.  The likelihood of one needing USD compared to Tongan pa'anga would be far greater (my US-centric viewpoint is showing...).

**Comment by bee-san** [comment]
Hmmm. Not sure about that. The symbol for the US Dwollar is barely ever used outside of smaller countries like the US. Where as every single person can recgonise the symbol for the Tongan pa'anga.

**Comment by samwho** [comment]
I'm easily able to type the dollar sign, so don't feel much need to add it here. I'm not building a generic "find all symbols" tool, this is a for-me tool that's primarily for finding symbols I have difficulty remembering how to type.

I recommend something like https://symbl.cc/ for a more generic tool.

**Comment by samwho** [comment]
Actually no, that's not right. I've added this here https://github.com/samwho/symbol.wtf/commit/742f3ce1d31f61c93ed8e9f9065134a1f99efcfa and made sure to add you as a co-author @otobrglez. Thank you for your contribution, and thank you for teaching me about Tonga @bee-san 🙏

**Comment by otobrglez** [comment]
I'm sorry for the geography/fiscal lesson. We all learned today! ✌️😉

**Pull request closed without merging**
